default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: dasha
  timeout: 5000
  reaping_frequency: 30
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_hirer_development
  password: 123

test:
  <<: *default
  database: api_hirer_test
  password: 123

production:
  <<: *default
  database: api_hirer_production
  password: 123
